version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - 'database'
      - 'seed'
    ports:
      - '80:4507'

  database:
    image: mongo:4.2.7

  seed:
    build: .
    command: npm run seed
