version: '3'

services:
  client:
    build: .
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    image: mongo
    # ports:
    #   - '27017:27017'

  # seed:
  #   build: ./server/seed.js
  #   links:
  #     - 'database'